size=  200  dt=  0.004  nteps= 250.0
Traceback (most recent call last):
  File "main.py", line 47, in <module>
    R.op(GodBu.gb,In,0.1)
  File "/usr/local/lib/python3.6/dist-packages/numba/jitclass/boxing.py", line 62, in wrapper
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/numba/dispatcher.py", line 344, in _compile_for_args
    reraise(type(e), e, None)
  File "/usr/local/lib/python3.6/dist-packages/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed at nopython (nopython frontend)
Failed at nopython (nopython frontend)
Untyped global name 'In': cannot determine Numba type of <class 'object'>

File "RK3TVD.py", line 31:
    def op(self,Meth,InOut,dt):
        <source elided>
        #Meth(InOut,self.u1)
        self.W.weno(Meth,In,Out)
        ^

[1] During: resolving callee type: BoundFunction((<class 'numba.types.misc.ClassInstanceType'>, 'op') for instance.jitclass.RK3TVD#130ff28<c21:float64,c22:float64,c31:float64,c32:float64,size:int32,u1:array(float64, 1d, A),u2:array(float64, 1d, A),W:DeferredType#140569995736512>)
[2] During: typing of call at <string> (3)


File "<string>", line 3:


This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new

